apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develeapgitops
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./jenkins-demo
    repoURL: https://github.com/shay79il/DeveleapGitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
